# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Erik Pillon 
# Description of the Site
description: Mathematician, Physics enthusiast, Pizza lover
# URL of Image of the Site
site-image: /WhatATheme/assets/images/nerdy
# Keywords of the Site
site-keywords: Erik Pillon, ErikPillon
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
# heroimage: https://images.pexels.com/photos/220444/pexels-photo-220444.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940
heroimage: ../images/nerdy.jpeg

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: erik.pillon@gmail.com
facebook_username: pi.ErikPillon
twitter_username: 
instagram_username: erikpillon
linkedin_username: erikpillon
github_username:  erikpillon
youtube_channel_id: 
reddit_username: 
behance_username: 
dribbble_username: 
spotify_username: 

# Google Analytics
google-analytics: G-TVDC8TKG2W

# Disqus
disqus-shortname: erikpillon

  # Name of the Author
author-name: Erik Pillon
# URL for the Image of the Author
author-image: ../images/pic.png
# 60 Words About the Author
author-about: Hi, and thanks for passing by! I’m a Backend Developer with a background in pure Mathematics and Theoretical Physics.
            As a former scientist and actual software developer with a passion for science and technology, 
            I have spent the last several years developing software applications and tools that help scientists and researchers to collect, visualize and understand data.
            </br>
            In my free time I like to read everything that goes from pop science to philosophy, economics and history (check out my 
            <a href="https://the52ndbook.github.io">blog</a>); 
            I'm a great Ferrari fan and I love analyzing GP data (check out <a href="https://f1analytics.github.io">F1 Analytics</a> and let me know what you think)
            </br>
            </br>
            <b>Outreaching</b></br>
            In my previous life as researcher, I focused on the development of efficient numerical techniques based on the rigorous mathematical threatment of non-abelian gauge structures 
            underlying non-adiabatic phenomena in physics and chemistry, namely the (molecular) Aharonov-Bohm effect. 
            You can find an accessible introduction to my work in <a href="/assets/forum_EP.pdf">this article</a>.</br> 
            Alongside my doctoral studies, I took part to several science communcation projects, both online and offline. 
            I've been writing pop science articles since 2016 on <a href="www.mathone.it">Mathone.it</a>, on my Facebook pages (<a href="https://www.facebook.com/Phi6Passion">Phi6 Passion</a> and 
            <a href="https://www.facebook.com/LaGaiaScienzaF">La Gaia Scienza</a>) and on the platform Quora. 
            More recently, I joined the PhD Students Association <a href="https://luxdoc.uni.lu">LuxDoc</a>, where I also had the pleasure of serving many roles in the committee board.
            As President, I had the opportunity of supervising and co-organize several outreaching activities that involved either Private and Public Stakeholders, 
            from the 
            <a href="https://www.youtube.com/watch?v=1I_873Sr14o&t=14s">Luxembourgish ScienceSlam</a>
            to the "3 Minutes Thesis" Competition. 
            Feel free to visit my Projects page for further details. 

# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/erikpillon

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
