# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Erik Pillon 
# Description of the Site
description: Mathematician, Physics enthusiast, Pizza lover
# URL of Image of the Site
site-image: /WhatATheme/assets/images/nerdy
# Keywords of the Site
site-keywords: Erik Pillon, ErikPillon
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
# heroimage: https://images.pexels.com/photos/220444/pexels-photo-220444.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940
heroimage: ../images/nerdy.jpeg

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
resume: resume_scicomm.pdf
email: erik.pillon@gmail.com
facebook_username: pi.ErikPillon
twitter_username: 
instagram_username: erikpillon
linkedin_username: erikpillon
github_username:  erikpillon
youtube_channel_id: 
reddit_username: 
behance_username: 
dribbble_username: 
spotify_username: 

# Google Analytics
google-analytics: G-TVDC8TKG2W

# Disqus
disqus-shortname: erikpillon

  # Name of the Author
author-name: Erik Pillon
# URL for the Image of the Author
author-image: ../images/pic.png
# 60 Words About the Author
author-about: Mathematician by training, I focused during my postgraduate studies on the development of efficient 
              numerical techniques for the simulation of non-adiabatic phenomena in physics and chemistry. 
              My other scientific interests cover the development and improvements of Machine Learning techniques 
              for the prediction of molecular and chemical properties. You can find an accessible introduction to my work in
              <a href="/assets/forum_EP.pdf">this article</a>.</br> 
              </br>
              <b>Outreaching</b></br>
              I started cultivating my passion fort Science Communication during my Bachelor Studies in 2016, 
              when I started sharing my interests in pop science books 
              through series of articles on <a href="www.mathone.it">Mathone.it</a>, on my Facebook pages 
              (<a href="https://www.facebook.com/Phi6Passion">Phi6 Passion</a> and 
              <a href="https://www.facebook.com/LaGaiaScienzaF">La Gaia Scienza</a>) and on the platform Quora. 
              More recently, I joined the PhD Students Association <a href="https://luxdoc.uni.lu">LuxDoc</a>, 
              where I also had the pleasure of serving many roles in the committee board.
              As President, I had the opportunity of supervising and co-organize several outreaching activities 
              that involved either Private and Public Stakeholders, 
              from the Luxembourgish ScienceSlam to the "3 Minutes Thesis" Competition. 
              Feel free to visit my Projects page for further details.</br> 
              <br>
              </br>
              <b>Additional Interests and Free Time</b><br>
              Amateur chess player and numismatist; former cyclist and cycling coach. 
              I'm a great Formula 1 fan and I spend (maybe too much) free time cooking...
              Avid reader, I consume everything that ranges between phylosophy, history, popular science and economics. 
              My hobbies include boardgames, 
              solving computational/mathematical puzzles.
              <br>
              </br>
              Feel free to write me in a linear combination of languages among Italian, English and French. 
              German will join the party soon ;)
              The languages that I prefer, instead, are Fortran, Julia and Python, even if I also write a 
              considerable amount of code in Bash and Matlab.

# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/erikpillon

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
